/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSimulateRouteImport } from './routes/_app.simulate'
import { Route as AppMpesaRouteImport } from './routes/_app.mpesa'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppStudentsIdRouteImport } from './routes/_app.students.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSimulateRoute = AppSimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => AppRoute,
} as any)
const AppMpesaRoute = AppMpesaRouteImport.update({
  id: '/mpesa',
  path: '/mpesa',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIdRoute = AppStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/mpesa': typeof AppMpesaRoute
  '/simulate': typeof AppSimulateRoute
  '/students/$id': typeof AppStudentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/mpesa': typeof AppMpesaRoute
  '/simulate': typeof AppSimulateRoute
  '/students/$id': typeof AppStudentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/mpesa': typeof AppMpesaRoute
  '/_app/simulate': typeof AppSimulateRoute
  '/_app/students/$id': typeof AppStudentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/mpesa'
    | '/simulate'
    | '/students/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/mpesa'
    | '/simulate'
    | '/students/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/mpesa'
    | '/_app/simulate'
    | '/_app/students/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/simulate': {
      id: '/_app/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof AppSimulateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mpesa': {
      id: '/_app/mpesa'
      path: '/mpesa'
      fullPath: '/mpesa'
      preLoaderRoute: typeof AppMpesaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$id': {
      id: '/_app/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AppStudentsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMpesaRoute: typeof AppMpesaRoute
  AppSimulateRoute: typeof AppSimulateRoute
  AppStudentsIdRoute: typeof AppStudentsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMpesaRoute: AppMpesaRoute,
  AppSimulateRoute: AppSimulateRoute,
  AppStudentsIdRoute: AppStudentsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
